# Test your FastAPI endpoints
###
GET http://127.0.0.1:8000/todos/
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTc1Mjk2ODgwMC4xNDgzMTl9.Or1Go-zCEYGkaUhfXmDZ3WFxFMY8KafgRspK3wgjz2YOFofYnnzdAgm9VzzBkYFZHuBVP3anFRhwmUOebS8ViyDigKud7oaqZUTNyys5kTX7HLGi0C63ZfjTIypOkucCMo2gVthg5O4MKLwPSOWRm-SdEknhsiDcrE7gbRF5_f5Y3cN75FfD3NUjfCudF_0llNBEgYz3kkAy-7gYRagvwu052x3GyV8yuelOYFyeR5_gEm9v-5EDnGpKkQfkxi2ufU8_zW8b3SAbaMxh7n3_xImapqtAnMu1zsPt9jP7-Uq7zKn5fw56ZVw_dz41lT6Mm9PYzXkLYrVLzRZa2z718A

###
GET http://127.0.0.1:8000/todos/3
Accept: application/json

###
POST http://127.0.0.1:8000/todos/
Accept: application/json
Content-Type: application/json

{
  "title": "offer",
  "description": "send offer of the day",
  "priority": 3,
  "completed": false,
  "owner": 1
}

###
PUT http://127.0.0.1:8000/todos/99
Accept: application/json
Content-Type: application/json

{
  "title": "new todo3",
  "description": "new_todo3",
  "priority": 1,
  "completed": false
}

###
PATCH http://127.0.0.1:8000/todos/6
Accept: application/json
Content-Type: application/json

{
  "completed": true
}

###
DELETE http://127.0.0.1:8000/todos/8
Accept: application/json