###
GET http://localhost:8000/users/
Accept: application/json

###
POST http://localhost:8000/users/
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "email": "admin@hotmail.com",
  "password": "12345678",
  "first_name": "admin",
  "last_name": "admin"
}